version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Initialize submodules if any
    - git submodule init
    - git submodule update
    # Install uv
    - pip install uv
    # Install dependencies using uv
    - uv sync
    # Build documentation with Zensical
    - uv run zensical build --clean
    # Copy build output to ReadTheDocs expected location
    - mkdir -p _readthedocs
    - cp -r site/ _readthedocs/html/

submodules:
  include: all
